"""empty message

Revision ID: c8f77b58c3ef
Revises: da7324df12ea
Create Date: 2025-02-17 01:10:07.457670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8f77b58c3ef'
down_revision = 'da7324df12ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_column('mass')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mass', sa.VARCHAR(length=250), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
