"""empty message

Revision ID: da7324df12ea
Revises: 369be17cb358
Create Date: 2025-02-14 20:52:33.153509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da7324df12ea'
down_revision = '369be17cb358'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('characters_id', sa.Integer(), nullable=True),
    sa.Column('planets_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['characters_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['planets_id'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('favourites')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favourites',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('characters_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('planets_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['characters_id'], ['characters.id'], name='favourites_characters_id_fkey'),
    sa.ForeignKeyConstraint(['planets_id'], ['planets.id'], name='favourites_planets_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='favourites_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favourites_pkey')
    )
    op.drop_table('favorites')
    # ### end Alembic commands ###
